### ISSUE TITLE
Accounts and Logins Review Ticket

### ISSUE THREAD

**Issue by Gaurish-Gaur** [Gaurish-Gaur/gaurishgaur-tri3#27]
Self Score 5/5 (Have all elements)

CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)

- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij

Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
- [x] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
- [x] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
- [x] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack #2 Add logout to CRUD screen
- [x] Hack #3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by connorw72** [comment]
# Krish Partner Grade - 5.5/5

Self Grade - 6/5

- [x] CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)

- [x] CB Create Task Coding requirements documented - Documented all requirements and how they are met.

- [x] Runtime of Code(with comments) on Replit/Intellij - Code is shown with comments of what different parts of the code meant.

Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.

- [x] Hack 1 Add Phone Number to Sign Up / Authorization screen - Phone number added

- [x] Hack 2 Add logout to CRUD screen - Logout added

- [x] Hack 3 Add login_required to another portion of the project - Login required added to life

- [] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
